version: '3'
services: 
  dbmysql:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: todolist
    ports:
      -"3308:3306"
  admin:
    image: adminer
    ports: 
      - "8080:8080"